CREATE TABLE POSITIONS (
  RACKID NUMBER(6) NOT NULL,
  PROW NUMBER(6) NOT NULL,
  PCOLUMN NUMBER(6) NOT NULL,
  ITEMID NUMBER(6),
  QUANTITY NUMBER(6) NOT NULL,
PRIMARY KEY(RACKID, PROW, PCOLUMN)
);

GRANT ALL ON POSITIONS TO PUBLIC;
