CREATE TABLE RACKS (
  ID NUMBER(6) NOT NULL,
  DESCRIPTION VARCHAR(128),
  STOREID NUMBER(6) NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT uni_id_storeid UNIQUE(ID, STOREID)
);

GRANT ALL ON RACKS TO PUBLIC;
