CREATE TABLE POSITIONS (
  RACKID INTEGER NOT NULL,
  PROW INTEGER NOT NULL,
  PCOLUMN INTEGER NOT NULL,
  ITEMID INTEGER,
  QUANTITY INTEGER NOT NULL,
PRIMARY KEY(RACKID, PROW, PCOLUMN)
);
GRANT ALL ON POSITIONS TO PUBLIC;
